CREATE TABLE IF NOT EXISTS reactive_board (
    board_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255),
    writer_id BIGINT,
    content TEXT,
    create_date TIMESTAMP,
    update_date TIMESTAMP
);

CREATE TABLE IF NOT EXISTS anonymous_post (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    content TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);